### ISSUE TITLE
Bloodveld locations

### ISSUE THREAD

**Issue by KarimKabbara00** [LeeOkeefe/slayer-assistant-plugin#38]
Does not show Kourend Dungeon as location for mutated bloodvelds

**Comment by LeeOkeefe** [comment]
You mentioned that the mutated bloodveld is not shown as a slayer monster, and its locations are not included because it is considered a variant of the bloodveld. As such, it counts towards the bloodveld slayer task. This is similar to how K’ril Tsutsaroth can be killed as part of a demons task. Including variants in the searchable task list could be confusing, given the numerous potential variants for a single monster type.

However, this does raise attention to this information being useful to players. Instead of listing variants separately, it would be more effective to select the main slayer task monster (e.g., bloodveld) and then include information about all its variants (e.g., mutated bloodveld) within the details of that task. This approach maintains clarity while providing comprehensive information.

I appreciate the suggestion and will have a think of how this could best be integrated.
